# Generated by Django 4.2 on 2023-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_is_active_alter_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_score",
            field=models.PositiveIntegerField(default=0, verbose_name="User score"),
        ),
    ]
