# Generated by Django 4.2 on 2023-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_user_user_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Consumer"), (2, "Provider")],
                default=1,
                verbose_name="User type",
            ),
        ),
    ]
