# Generated by Django 4.2 on 2023-07-15 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.CharField(
                default=uuid.UUID("52ff073d-3f29-4509-b87f-5131aa4e31e3"),
                max_length=150,
                unique=True,
            ),
        ),
    ]
