# Generated by Django 4.2 on 2023-07-15 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET("deleted_user"),
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
