# Generated by Django 4.2 on 2023-07-15 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="invoice_number",
            field=models.UUIDField(default=uuid.UUID("367bff4c-49d2-4868-bd48-5e64f06c34a9")),
        ),
    ]
