# Generated by Django 4.2 on 2023-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0002_alter_basket_created_time_alter_basket_is_paid_and_more"),
        ("transaction", "0003_alter_transaction_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="basket.basket",
                verbose_name="Basket",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="invoice_number",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Invoice number"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "paid"), (0, "pending"), (-10, "Not paid")],
                default=-10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Purchase"), (1, "Charge")], default=2, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="total",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Total"),
        ),
    ]
