# Generated by Django 4.2 on 2023-07-15 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0003_userscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_score",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
