# Generated by Django 4.2 on 2023-07-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0004_alter_userscore_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Purchase"), (1, "Charge")], default=2
            ),
        ),
    ]
