# Generated by Django 4.2 on 2023-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="total",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
