# Generated by Django 4.2 on 2023-07-15 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0006_alter_wallet_total"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserScore",
        ),
    ]
