# Generated by Django 4.2 on 2023-07-15 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0007_delete_userscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice_number",
            field=models.UUIDField(
                default=uuid.UUID("487ee36b-5be9-45d8-8150-c71437492963"),
                verbose_name="invoice number",
            ),
        ),
    ]
