# Generated by Django 4.2 on 2023-07-15 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0008_transaction_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="invoice_number",
            field=models.UUIDField(
                default=uuid.UUID("982a7116-62d1-4321-8940-9f97b61ee4b1"),
                verbose_name="invoice number",
            ),
        ),
    ]
