# Generated by Django 4.2 on 2023-07-15 14:19

from django.db import migrations, models
import django.db.models.deletion
import lib.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("shipping", "0002_shipping_is_deliverd"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping",
            name="user_address",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shippings",
                to="accounts.useraddress",
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="sending_date",
            field=models.DateField(validators=[lib.validators.validated_date]),
        ),
    ]
