# Generated by Django 4.2 on 2023-07-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_uuid"),
        ("shipping", "0003_shipping_user_address_alter_shipping_sending_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_line",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="shippingitem",
            name="shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_line",
                to="shipping.shipping",
            ),
        ),
    ]
