# Generated by Django 4.2 on 2023-07-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("product", "0004_alter_product_category_alter_product_provider_and_more"),
        ("shipping", "0004_alter_shippingitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping",
            name="delivery_method",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "digikala plus"),
                    (2, "digikala express"),
                    (3, "Provider"),
                ],
                default=2,
                verbose_name="Delivery method",
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="sending_date",
            field=models.DateField(
                validators=[lib.validators.validated_date], verbose_name="Shipping Date"
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_shipping",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="user_address",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shippings",
                to="accounts.useraddress",
                verbose_name="User Address",
            ),
        ),
        migrations.AlterField(
            model_name="shippingitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_line",
                to="product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="shippingitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="shippingitem",
            name="shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_line",
                to="shipping.shipping",
                verbose_name="Shipping",
            ),
        ),
    ]
