# Generated by Django 4.2 on 2023-07-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0004_alter_product_category_alter_product_provider_and_more"),
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Date"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is paid"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_baskets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="basketline",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="basket.basket",
                verbose_name="Basket",
            ),
        ),
        migrations.AlterField(
            model_name="basketline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="basketline",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
